service: liveet-api

provider:
    name: aws
    region: us-west-2
    runtime: provided.al2
    stage: ${opt:stage, 'staging'}
    httpApi:
        id: ppl2yu2v4c

functions:
    api:
        handler: index.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - 'arn:aws:lambda:us-west-2:209497400698:layer:php-74-fpm:29'
        events:
            -   httpApi: '*'

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
