name: CI

on:
  push:
    branches: [ test ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install serverless
        run: npm uninstall -g serverless && npm i -g serverless@1.68.0
      - name: Install PHP Composer dependencies
        uses: php-actions/composer@master
        with:
          php_version: 7.4
      - name: Install Assets
        run: npm install
      - name: Serverless Deploy Staging
        run: serverless deploy --region us-west-2 --stage staging --force --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}